kind: ConfigMap 
apiVersion: v1 
metadata:
  name: elasticsearch-configmap 
data:
  # Configuration values can be set as key-value properties
  database: mongodb
  # database_uri: mongodb://localhost:27017
